In [1]:
#import libaries
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns

pd.set_option('display.max_rows', None)

'''Create a numpy array called ‘height in inches’ from a list 10 of numbers: [66, 68, 71, 64, 61, 74, 64, 65, 70, 71]'''

In [2]:
height_in_inches = np.array([66, 68, 71, 64, 61, 74, 64, 65, 70, 71], dtype= 'f')
print(height_in_inches)

[66. 68. 71. 64. 61. 74. 64. 65. 70. 71.]


'''Create a new array called ‘height_in_feet’ and make its values equal to the values in the first array divided by 12.'''

In [4]:
height_in_feet = height_in_inches/12
print(height_in_feet)

[5.5       5.6666665 5.9166665 5.3333335 5.0833335 6.1666665 5.3333335
 5.4166665 5.8333335 5.9166665]


'''Create a 5x5 array of zeros.'''

In [6]:
Fiveby5Zeros = np.zeros((5,5))
print(Fiveby5)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


'''Create an array of random floating point numbers between 0 and 100.'''

In [8]:
np.random.rand((100))*100
#np.random.rand_sample((100))*100

array([20.97050482, 64.50914472, 50.59556259, 46.97076208, 21.64836285,
       67.60996179, 49.21391588, 47.88338722, 47.02538879, 50.9717267 ,
        0.30089113, 69.04829289, 53.56621695, 36.88321758, 97.30264257,
       16.26479831, 34.54470876, 68.52077016, 99.1211191 , 93.2649436 ,
       25.96564033, 55.01759583, 96.60031481, 44.82455343, 86.46476658,
       19.75960912, 54.04817024, 91.59240906, 93.44050054, 29.89670665,
       38.34395174, 85.43194338, 25.78069181, 72.94478541, 63.86197517,
       96.72100717, 35.32284863, 31.60267274,  8.75597069, 23.19962434,
       87.82159204,  2.27052393, 88.39983292,  7.46986241, 81.34567142,
       85.66494154, 99.39235996, 46.53674239, 92.72481104, 81.35403016,
       69.94930928, 21.56473052, 20.10510925, 37.76294006, 71.81724822,
       92.23145084,  6.21834751, 79.21874361, 95.09028878, 26.68024773,
       49.18223958, 47.62634165, 77.51776398, 57.85971916, 33.19368306,
       90.52206154, 65.74901695,  2.53374591, 21.38102439, 84.91

'''Create an array of numbers from 0 to 75 in increments of 5.'''

In [12]:
print(np.arange(0,80,5))
#np.arange(0,100)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75]
