In [1]:
import pandas as pd
import numpy as np

In [5]:
arr = np.array([2,4,6,8,10], dtype='i')
arr

array([ 2,  4,  6,  8, 10], dtype=int32)

In [6]:
#to show the data type
print(arr.dtype)
arr.dtype
arr

int32


array([ 2,  4,  6,  8, 10], dtype=int32)

In [8]:
#change the data type to a float
arr = np.array([2,4,6,8,19], dtype='f')
print(arr)

[ 2.  4.  6.  8. 19.]


In [9]:
#adding string values to an array
hometypes = np.array(['house','apartment', 'condo','tent', 'igloo' ])
hometypes

array(['house', 'apartment', 'condo', 'tent', 'igloo'], dtype='<U9')

In [ ]:
 = hometype.astype('string')

In [10]:
hometypes2 = pd.DataFrame(hometypes)
hometypes2

0
0      house
1  apartment
2      condo
3       tent
4      igloo

In [11]:
hometypes2.rename(columns = {0:"types"})

types
0      house
1  apartment
2      condo
3       tent
4      igloo

In [12]:
#2D array
a = np.array([[2,4,8], [10,12,14]])
print(a)

[[ 2  4  8]
 [10 12 14]]


In [14]:
#3D array
b = np.array([[2,4,8], [10,12,14], [16, 18, 20]])
print(b)
print(b.shape) #shape of the array

[[ 2  4  8]
 [10 12 14]
 [16 18 20]]
(3, 3)


In [15]:
c = np.array([[2,4], [10,12], [16, 18]])
print(c)
print(c.shape) #shape of the array

[[ 2  4]
 [10 12]
 [16 18]]
(3, 2)


In [16]:
d = np.array([[2,4,5], [10,12], [16, 18, 17]], dtype='object')
print(d)
print(d.shape)

[list([2, 4, 5]) list([10, 12]) list([16, 18, 17])]
(3,)


In [17]:
a[0,0]

2

In [18]:
a[1,2]

14

ValueError: operands could not be broadcast together with shapes (2,3) (3,3) 