In [1]:
import pandas as pd
import numpy as np

In [3]:
arr = np.array([2,4,6,8,10])
print(arr)

[ 2  4  6  8 10]


In [4]:
arr = np.array([2,4,6,8,10], dtype = 'i')
print(arr)

[ 2  4  6  8 10]


In [7]:
#to show the data type
print(arr.dtype)
arr.dtype
arr

int32


array([ 2,  4,  6,  8, 10], dtype=int32)

In [10]:
#Change the data type to a float
arr = np.array([2,4,6,8,10], dtype = 'f')
arr
print(arr)

[ 2.  4.  6.  8. 10.]


In [11]:
#Adding string values to an array
hometypes = np.array(['house','apartment','condo', 'tent', 'igloo'])
hometypes

array(['house', 'apartment', 'condo', 'tent', 'igloo'], dtype='<U9')

In [14]:
hometypes2= pd.DataFrame(hometypes)
hometypes2

0
0      house
1  apartment
2      condo
3       tent
4      igloo

In [15]:
hometypes2.rename(columns = {0:"types"})

types
0      house
1  apartment
2      condo
3       tent
4      igloo

In [16]:
#2D array
a = np.array([[2,4,8], [10,12,14]])
print(a)

[[ 2  4  8]
 [10 12 14]]


In [18]:
#3D array
b = np.array([[2,4,8], [10,12,14], [16,18,20]])
print(b)
print(b.shape) #shape of the array

[[ 2  4  8]
 [10 12 14]
 [16 18 20]]
(3, 3)


In [22]:
c = np.array([[2,4,5], [10,12], [16,18,7]], dtype = 'object')
print(c)
print(c.shape) #shape of the array

[list([2, 4, 5]) list([10, 12]) list([16, 18, 7])]
(3,)


In [24]:
d = np.array([[2,4,8,1], [10,12,14,3], [16,18,20,5],[22,24,26,7]])
print(d)
print(d.shape) #shape of the array

[[ 2  4  8  1]
 [10 12 14  3]
 [16 18 20  5]
 [22 24 26  7]]
(4, 4)


In [28]:
a = np.array([[2,4,8], [10,12,14]]) #a = np.array([[2,4,8], [10,12,14]])
a[0,0] #2
a[1,2] #14

14

In [31]:
d = np.array([[2,4,8,1], [10,12,14,3], [16,18,20,5],[22,24,26,7]])
print(d[2,1], d[3,1]) #18,24
print(d[0,2] +d[3,2] ) #8 + 26

18 24
34


In [33]:
d[-1,-1] #7 from the opposite end
d[-2,2]

20

In [34]:
d_copy = d.copy()
d_copy

array([[ 2,  4,  8,  1],
       [10, 12, 14,  3],
       [16, 18, 20,  5],
       [22, 24, 26,  7]])

In [36]:
#replacing a value within the array
d_copy[2,3] = 9
d_copy

array([[ 2,  4,  8,  1],
       [10, 12, 14,  3],
       [16, 18, 20,  9],
       [22, 24, 26,  7]])

In [37]:
d[1:3]

array([[10, 12, 14,  3],
       [16, 18, 20,  5]])

In [38]:
d[:2]

array([[ 2,  4,  8,  1],
       [10, 12, 14,  3]])

In [39]:
d[-3:-1]

array([[10, 12, 14,  3],
       [16, 18, 20,  5]])

In [40]:
d[1:]

array([[10, 12, 14,  3],
       [16, 18, 20,  5],
       [22, 24, 26,  7]])

In [56]:
type(d)
type(a)
hometypes.ndim #shows the number of axes
d.shape #shape of the array
d.size #size of the array
d.dtype #type of elements in the array
np.random.random((2,2))
np.zeros((3,4)) #array with zeros
np.arange(0,30,5)
np.linspace(0,5,10)
a.flatten() #converts multidimensional arrays into a single array
d.flatten()

array([ 2,  4,  8,  1, 10, 12, 14,  3, 16, 18, 20,  5, 22, 24, 26,  7])